language: python

python:
  - pypy
  - pypy3
  - 2.6
  - 2.7
  - 2.7_with_system_site_packages
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - python setup.py install
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - coverage erase

script:
  # Simple tests: just run some example commands with options
  - coverage run --append --include=./* vanity.py -h
  - coverage run --append --include=./* vanity.py --help
  - coverage run --append --include=./* vanity.py vanity pillow
  - coverage run --append --include=./* vanity.py vanity pillow -q
  - coverage run --append --include=./* vanity.py --quiet vanity pillow
  - coverage run --append --include=./* vanity.py pil
  - coverage run --append --include=./* vanity.py vanity==0.0.0
  - coverage run --append --include=./* vanity.py vanity==1.0
  - coverage run --append --include=./* vanity pillow --pattern "Pillow-3.0.0.*win32.*py3.2|Pillow-3.0.0.*cp32.*win32"

after_success:
  - coverage report
  - travis_retry pip install coveralls
  - coveralls

  - travis_retry pip install pep8 pyflakes
  - pep8 --statistics --count *.py
  - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
